kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: isd-analysis-nr
spec:
  args:
    - name: canary-hash
    - name: baseline-hash
  metrics:
    - name: isd-analysis-score
      count: 1
      initialDelay: 2s
      provider:
        opsmx:
          gateUrl: https://isd-dev.argo-dev.opsmx.net/
          lifetimeHours: "0.05"
          application: isd-for-nr-canary
          user: admin
          threshold:
            pass: 80
            marginal: 60
          services:
          - metricTemplateName: demo-custom
            metricScopeVariables: "app_key,pod_key"
            baselineMetricScope: "issugen-baseline,{{args.baseline-hash}}"
            canaryMetricScope: "issugen-baseline,{{args.canary-hash}}"
