apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: oes-argo-rollout-demo
spec:
  replicas: 5
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: oes-argo-rollout-demo
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus_io_path: '/mgmt/prometheus'
        prometheus_io_port: '8088'    
      labels:
        app: oes-argo-rollout-demo
    spec:
      containers:
        - name: rollouts-baseline
          image: docker.io/opsmxdev/issuegen:v3.0.3
          imagePullPolicy: Always
          ports:
            - containerPort: 8088
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: { duration: 31s }
        - experiment:
            analyses:
            - name : oes-analysis-isd
              requiredForCompletion: true
              templateName: oes-analysis-isd
            templates:
              - name: baseline
                specRef: stable
              - name: canary
                specRef: canary
        - setWeight: 60
        - pause: { duration: 30s }                 
        - setWeight: 80
        - pause: { duration: 30s }
