apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: oes-analysis-isd
spec:
  args:
  - name: start-time
  - name: end-time
  metrics:
    - name: oes-analysis-isd
      provider:
        opsmx:
          gateUrl: https://ds312.isd-dev.opsmx.net/
          user: "admin"
          application: testapp
          baselineStartTime: "{{args.start-time}}"
          canaryStartTime: "{{args.start-time}}"
          endTime: "{{args.end-time}}"
          threshold:
            pass: 80
            marginal: 60
