kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: qa-analysis
spec:
  args:
    - name: canary-hash
    - name: baseline-hash
  metrics:
    - name: qa-analysis
      count: 1
      initialDelay: 30s
      provider:
        opsmx:
          gateUrl: https://isd-dev.argo-dev.opsmx.net/
          application: loganalysisapplication
          user: admin
          lifetimeHours: "0.05"
          threshold:
            pass: 80
            marginal: 60
          services:
          - logTemplateName: RegularIsdTemp2
            logScopeVariables: "kubernetes.container_name"
            baselineLogScope: "baseapp-rest-1"
            canaryLogScope: "canaryapp-rest-1
